Getting very close, now just need to deal with removal of already checked positive preconditions...
In [6]: %run random_world.py

In [7]: prob = RandomProblem1()

In [8]: applicables = set()

In [9]: prob.add_applicable_actions('op1', applicables)
Initial set of preconditions is (set([]), set([('R', 'x3', 'x1'), ('S', 'x1', 'x2')]))
using positive_precondition ('R', 'x3', 'x1')
Using state proposition ('R', 'B', 'B')
sigma_prime = {'x3': 'B', 'x1': 'B'}
using positive_precondition ('S', 'x1', 'x2')
Using state proposition ('R', 'B', 'B')
Using state proposition ('R', 'C', 'B')
Using state proposition ('S', 'C', 'B')
sigma_prime = False
Using state proposition ('S', 'B', 'B')
sigma_prime = {'x2': 'B', 'x3': 'B', 'x1': 'B'}
Using state proposition ('S', 'A', 'C')
sigma_prime = False
Using state proposition ('R', 'C', 'B')
sigma_prime = {'x3': 'C', 'x1': 'B'}
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-849ad8286190> in <module>()
----> 1 prob.add_applicable_actions('op1', applicables)

/home/hobs/src/coursera/aiplan/random_world.py in add_applicable_actions(self, action_name, applicable_actions, remaining_preconditions, action_kwargs)
    262                 if new_kwargs:
    263                     new_preconditions = tuple(remaining_preconditions)
--> 264                     new_preconditions[True].remove(pos_precon)
    265                     self.add_applicable_actions(action_name, applicable_actions, new_preconditions, new_kwargs)
    266

KeyError: ('R', 'x3', 'x1')

In [10]: applicables
Out[10]: {('op1', (('x2', 'B'), ('x3', 'B'), ('x1', 'B')))}